# Generated by Django 4.2 on 2024-05-24 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='like_counts',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
