# Generated by Django 4.2 on 2024-05-22 11:02

import Post.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(upload_to=Post.models.get_image_upload_path),
        ),
    ]
