# Generated by Django 4.2 on 2024-05-28 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0003_remove_comment_depth_comment_like_counts'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comment_likes',
            new_name='like_comments',
        ),
    ]
