# Generated by Django 4.2 on 2024-05-28 03:02

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('gender', models.CharField(choices=[('남자', '남자'), ('여자', '여자')], max_length=20)),
                ('age', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(120)])),
                ('height', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(50), django.core.validators.MaxValueValidator(250)])),
                ('weight', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(30), django.core.validators.MaxValueValidator(290)])),
                ('current_medications_or_supplements', models.TextField()),
                ('allergies', models.TextField()),
                ('exercise_frequency_per_week', models.CharField(choices=[('0', '주0회'), ('1', '주1회'), ('2~3', '주2~3회'), ('4이상', '주4회 이상')], max_length=20)),
                ('average_sleep_hours_per_day', models.CharField(choices=[('5~8', '5~8시간'), ('8~10', '8~10시간'), ('10~12', '10~12시간'), ('12이상', '12시간 이상')], max_length=20)),
                ('smoking_status', models.CharField(choices=[('예', '예'), ('아니오', '아니오')], max_length=20)),
                ('alcohol_consumption', models.CharField(choices=[('마시지 않음', '마시지 않음'), ('주1~2회', '주1~2회'), ('주3회 이상', '주3회 이상')], max_length=20)),
                ('average_meals_per_day', models.CharField(choices=[('1', '1회'), ('2', '2회'), ('3', '3회'), ('4이상', '4회 이상')], max_length=20)),
                ('main_foods', models.CharField(choices=[('고기 위주', '고기 위주'), ('채식 위주', '채식 위주'), ('균형잡힌 식단', '균형잡힌 식단')], max_length=20)),
                ('snacks', models.CharField(choices=[('과일', '고기 위주'), ('견과류', '채식 위주'), ('패스트푸드', '패스트푸드'), ('과자', '고기 위주'), ('OTHER', '기타')], default='과일', max_length=100)),
                ('snacks_other', models.CharField(blank=True, max_length=100)),
                ('health_goals', models.CharField(choices=[('체중감량', '체중감량'), ('근육증가', '근육증가'), ('면역력 강화', '면역력 강화'), ('피부 건강', '피부 건강'), ('에너지 증진', '에너지 증진'), ('OTHER', '기타')], default='체중감량', max_length=100)),
                ('health_goals_other', models.CharField(blank=True, max_length=100)),
                ('interested_supplements', models.CharField(choices=[('비타민', '비타민'), ('미네랄', '미네랄'), ('단백질 보충제', '단백질 보충제'), ('오메가 3', '오메가 3'), ('OTHER', '기타')], default='비타민', max_length=100)),
                ('interested_supplements_other', models.CharField(blank=True, max_length=100)),
                ('specific_health_issues_to_improve', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='survey', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SurveyResults',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommended_nutrients_1', models.TextField()),
                ('recommended_nutrients_2', models.TextField()),
                ('recommended_nutrients_3', models.TextField()),
                ('synergistic_nutrients_1', models.TextField()),
                ('synergistic_nutrients_2', models.TextField()),
                ('synergistic_nutrients_3', models.TextField()),
                ('antagonistic_nutrients_1', models.TextField()),
                ('antagonistic_nutrients_2', models.TextField()),
                ('antagonistic_nutrients_3', models.TextField()),
                ('alternative_foods_1', models.TextField()),
                ('alternative_foods_2', models.TextField()),
                ('alternative_foods_3', models.TextField()),
                ('incompatible_foods_1', models.TextField()),
                ('incompatible_foods_2', models.TextField()),
                ('incompatible_foods_3', models.TextField()),
                ('survey_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='survey', to='Survey.surveyinfo')),
            ],
        ),
    ]
