# Generated by Django 4.2 on 2024-05-27 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Survey', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveyinfo',
            name='health_goals_other',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='surveyinfo',
            name='interested_supplements_other',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='surveyinfo',
            name='snacks_other',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
