# Generated by Django 4.2 on 2024-06-07 11:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Survey', '0002_know_vitamins'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveyinfo',
            name='age',
            field=models.PositiveIntegerField(max_length=20, validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(120)]),
        ),
        migrations.AlterField(
            model_name='surveyinfo',
            name='snacks',
            field=models.CharField(choices=[('과일', '과일 위주'), ('견과류', '견과류 위주'), ('패스트푸드', '패스트푸드'), ('과자', '디저트 위주'), ('OTHER', '기타')], default='과일', max_length=100),
        ),
        migrations.AlterField(
            model_name='surveyinfo',
            name='specific_health_issues_to_improve',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
    ]
