# Generated by Django 4.2 on 2024-06-11 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Survey', '0003_alter_surveyinfo_age_alter_surveyinfo_snacks_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Know_Vitamins',
            new_name='KnowVitamins',
        ),
    ]
