# Generated by Django 4.2 on 2024-06-12 09:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Survey', '0004_rename_know_vitamins_knowvitamins'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='KnowVitamins',
            new_name='Know_Vitamins',
        ),
        migrations.AlterField(
            model_name='surveyinfo',
            name='age',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(120)]),
        ),
    ]
